### ISSUE TITLE
Very nice collection!

### ISSUE THREAD

**Issue by kellertuer** [andyjm3/Awesome-Riemannian-Optimization#1]
Thanks for such a great initiative to collect these!
I have a few small questions.

1, One could add authors to the single papers maybe?
2. One could maybe do this slightly generic collecting e.g. BibTeX entries, or in a yaml file with the category attached and render that on a homepage in the long run? Just an idea, if you want to keep this a simple md file that is also fine.

I can add a few papers in the area nonsmooth/constraint the next few days.

**Comment by andyjm3** [comment]
Thank you for the great suggestions! The authors and bibtex info could be added in the long run. Currently I prefer it to be concise as more papers are still being added. 

For the nonsmooth/constraint area, feel free to add any papers! Thank you!
